// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

enum EntityType {
  Character,
  NPC,
  Item,
  Location,
  Region,
  Quest,
  Faction
}

enum EventType {
  CombatOutcome,
  QuestComplete,
  NPCDeath,
  Discovery,
  FactionChange,
  Death,
  GameEvent
}
