// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Characters, CharactersData } from "./tables/Characters.sol";
import { Deaths, DeathsData } from "./tables/Deaths.sol";
import { Items, ItemsData } from "./tables/Items.sol";
import { Epochs, EpochsData } from "./tables/Epochs.sol";
