"""Cartographer crew — WFC-scaffolded ASCII terrain art for locations."""

from memento.core import Agent, Crew, Task, Process, LLM
from memento.config import get_model_for_crew
from memento.tools.art_validation import validate_art
from memento.tools.art_tools import generate_terrain_tool


def make_cartographer_crew(
    location_name: str,
    description: str,
    mood: str,
    biome: str = "default",
    width: int = 35,
    height: int = 20,
) -> Crew:
    """Build a crew that generates ASCII terrain art from a WFC scaffold."""
    model = get_model_for_crew("ascii_art")

    artist = Agent(
        role="Terrain Artist",
        goal="Add atmospheric detail to ASCII terrain scaffolds for a dark fantasy MUD",
        backstory=(
            f"You receive a {width}x{height} ASCII terrain scaffold generated by a "
            f"Wave Function Collapse algorithm. The scaffold has structural elements "
            f"(walls, floors, doors, water, paths) already placed.\n\n"
            f"YOUR JOB: Add atmospheric detail WITHIN the existing structure.\n\n"
            f"RULES:\n"
            f"- PRESERVE all wall and door positions — do not move or remove them\n"
            f"- DETAIL floor and empty regions with mood-appropriate characters\n"
            f"- Add narrative elements: furniture, debris, vegetation, light sources\n"
            f"- Final output must be exactly {height} lines, each exactly {width} characters\n"
            f"- Use the generate_terrain tool with biome='{biome}' to get the scaffold first\n\n"
            f"CHARACTER PALETTE:\n"
            f"- Standard ASCII: # . : | / \\ - _ ~ ^ * @ ' \" and spaces\n"
            f"- Box-drawing: ═ ║ ╔ ╗ ╚ ╝ ╦ ╩ ╠ ╣ ╬ ─ │ ┌ ┐ └ ┘\n"
            f"- Block elements: ░ ▒ ▓ █ ▄ ▀\n\n"
            f"After detailing, validate with validate_art tool "
            f"(expected_width={width}, expected_height={height})."
        ),
        tools=[generate_terrain_tool, validate_art],
        llm=LLM(model=model),
    )

    critic = Agent(
        role="Terrain Critic",
        goal="Ensure terrain art preserves structure and evokes the right atmosphere",
        backstory=(
            "You evaluate ASCII terrain art for a dark-fantasy MUD. Your criteria:\n\n"
            "1. STRUCTURAL INTEGRITY — walls, doors, and borders from the scaffold are preserved\n"
            "2. ATMOSPHERIC QUALITY — does it evoke the intended mood?\n"
            "3. READABILITY — can you identify rooms, corridors, features at a glance?\n"
            "4. DIMENSIONAL COMPLIANCE — correct width and height, no ragged lines\n"
            "5. PALETTE DISCIPLINE — only approved characters used\n\n"
            "If the art meets all criteria, respond with exactly 'APPROVED'.\n"
            "Otherwise, provide specific feedback with line numbers."
        ),
        tools=[],
        llm=LLM(model=model),
    )

    scaffold_task = Task(
        description=(
            f"Use the generate_terrain tool to create a scaffold for biome '{biome}' "
            f"with width={width}, height={height}. Then add atmospheric detail for "
            f"the location '{location_name}'.\n\n"
            f"Description: {description}\n"
            f"Mood: {mood}\n\n"
            f"Preserve all structural elements from the scaffold. Detail the floor "
            f"and empty spaces with mood-appropriate characters and narrative elements.\n\n"
            f"Output ONLY the final detailed ASCII art — exactly {height} lines, "
            f"each exactly {width} characters."
        ),
        expected_output=f"Exactly {height} lines of detailed ASCII art, each exactly {width} characters wide",
        agent=artist,
    )

    critique_task = Task(
        description=(
            "Evaluate the terrain art. Check that structural elements (walls, doors) "
            "from the scaffold are preserved, atmosphere matches the mood, and "
            "dimensions are correct.\n\n"
            "If it meets all criteria, respond with exactly: APPROVED\n"
            "Otherwise, provide specific feedback with line numbers."
        ),
        expected_output="Either 'APPROVED' or specific revision feedback",
        agent=critic,
        context=[scaffold_task],
    )

    revise_task = Task(
        description=(
            "Revise the terrain art based on the critic's feedback. "
            "If the critique was 'APPROVED', reproduce the art unchanged.\n\n"
            f"Output ONLY the raw ASCII art — exactly {height} lines, "
            f"each exactly {width} characters. No commentary."
        ),
        expected_output=f"Exactly {height} lines of revised ASCII art, each exactly {width} characters wide",
        agent=artist,
        context=[scaffold_task, critique_task],
    )

    validate_task = Task(
        description=(
            "Run the validate_art tool on the revised art with "
            f"expected_width={width} and expected_height={height}. "
            "If validation fails, fix and re-validate. "
            "Output ONLY the final validated ASCII art."
        ),
        expected_output="Final ASCII art that passes dimensional validation",
        agent=artist,
        context=[revise_task],
    )

    return Crew(
        agents=[artist, critic],
        tasks=[scaffold_task, critique_task, revise_task, validate_task],
        process=Process.sequential,
    )
