"""Chain writer — sends transactions to the MUD World contract via web3.

Loads the IWorld ABI from the compiled contracts and uses web3 to encode
and send transactions to the World contract on Anvil/Redstone.
"""

import asyncio
import json
import logging
import os
from pathlib import Path

logger = logging.getLogger(__name__)

_w3 = None
_contract = None
_account = None
_world_address: str = ""

# Path to the compiled IWorld ABI (generated by `mud build`)
# Try multiple paths — gateway vs engine vs project root
_PROJECT_ROOT = Path(__file__).resolve().parents[4]
_ABI_CANDIDATES = [
    _PROJECT_ROOT / "contracts/packages/contracts/out/IWorld.sol/IWorld.abi.json",
    Path("/home/at0x/Vaults/Bonfires/memento-mori/contracts/packages/contracts/out/IWorld.sol/IWorld.abi.json"),
]
_ABI_PATH = next((p for p in _ABI_CANDIDATES if p.exists()), _ABI_CANDIDATES[0])


def _get_contract():
    """Lazy-init web3 connection and contract instance."""
    global _w3, _contract, _account, _world_address
    if _w3 is not None:
        return _w3, _contract, _account

    try:
        from web3 import Web3

        rpc = os.getenv("REDSTONE_RPC", "http://localhost:8545")
        _world_address = os.getenv("MUD_WORLD_ADDRESS", "")
        pk = os.getenv("ENGINE_PRIVATE_KEY", "")

        if not _world_address or not pk:
            logger.info("Chain writer: missing MUD_WORLD_ADDRESS or ENGINE_PRIVATE_KEY")
            return None, None, None

        _w3 = Web3(Web3.HTTPProvider(rpc))
        _account = _w3.eth.account.from_key(pk)

        # Load ABI
        if _ABI_PATH.exists():
            abi = json.loads(_ABI_PATH.read_text())
            _contract = _w3.eth.contract(
                address=Web3.to_checksum_address(_world_address),
                abi=abi,
            )
            logger.info("Chain writer ready: world=%s rpc=%s", _world_address[:10], rpc)
        else:
            logger.warning("IWorld ABI not found at %s — chain writes disabled", _ABI_PATH)
            return _w3, None, _account

    except ImportError:
        logger.warning("web3 not installed — chain writes disabled")
    except Exception:
        logger.warning("Chain writer init failed", exc_info=True)

    return _w3, _contract, _account


async def call_system(function_sig: str, args: list) -> bool:
    """Call a MUD system function on the World contract.

    Args:
        function_sig: Namespaced function name (e.g. 'memento__setPosition')
        args: Arguments matching the function signature

    Returns:
        True on success, False on failure.
    """
    try:
        w3, contract, account = _get_contract()
        if not w3 or not contract or not account:
            logger.debug("Chain writer not ready — skipping %s", function_sig)
            return False

        # Get the contract function by name
        fn = getattr(contract.functions, function_sig, None)
        if fn is None:
            logger.warning("Function %s not found in IWorld ABI", function_sig)
            return False

        # Convert hex strings to bytes for bytes32 params
        converted_args = []
        for a in args:
            if isinstance(a, str) and a.startswith("0x") and len(a) == 66:
                converted_args.append(bytes.fromhex(a[2:]))
            else:
                converted_args.append(a)

        # Build and send transaction
        tx = fn(*converted_args).build_transaction({
            "from": account.address,
            "nonce": w3.eth.get_transaction_count(account.address),
            "gas": 2_000_000,
            "gasPrice": w3.eth.gas_price,
        })
        signed = account.sign_transaction(tx)
        tx_hash = await asyncio.to_thread(w3.eth.send_raw_transaction, signed.raw_transaction)
        receipt = await asyncio.to_thread(w3.eth.wait_for_transaction_receipt, tx_hash, timeout=10)

        if receipt["status"] == 1:
            logger.info("Chain write OK: %s tx=%s gas=%d", function_sig, tx_hash.hex()[:12], receipt["gasUsed"])
            return True
        else:
            # Try to get revert reason
            try:
                w3.eth.call(tx, receipt["blockNumber"])
            except Exception as revert_err:
                logger.warning("Chain write reverted: %s reason=%s", function_sig, revert_err)
            else:
                logger.warning("Chain write reverted: %s tx=%s (no revert reason)", function_sig, tx_hash.hex()[:12])
            return False

    except Exception:
        logger.warning("Chain write failed: %s", function_sig, exc_info=True)
        return False
