// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { EntityType } from "../common.sol";

/**
 * @title ICharacterSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ICharacterSystem {
  function memento__registerCharacter(bytes32 id, string memory name, address wallet, EntityType entityType) external;

  function memento__killCharacter(
    bytes32 characterId,
    string memory cause,
    string memory location,
    uint256 tick
  ) external;

  function memento__levelUp(bytes32 characterId, uint32 newLevel) external;
}
