// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IEpochSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IEpochSystem {
  function memento__commitEpoch(
    bytes32 id,
    bytes32 stateRoot,
    uint256 tick,
    uint32 entityCount,
    string memory ipfsCid,
    string memory metadata
  ) external;
}
