// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { EventType } from "../common.sol";

/**
 * @title IEventSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IEventSystem {
  function memento__recordEvent(
    bytes32 id,
    EventType eventType,
    string memory actors,
    string memory location,
    string memory summary,
    uint256 tick
  ) external;
}
