// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IItemSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IItemSystem {
  function memento__registerItem(
    bytes32 id,
    string memory name,
    string memory rarity,
    bytes32 ownerId,
    bytes32 locationId
  ) external;

  function memento__transferItem(bytes32 itemId, bytes32 newOwnerId) external;

  function memento__dropItem(bytes32 itemId, bytes32 locationId) external;
}
