// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ILocationSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ILocationSystem {
  function memento__registerLocation(
    bytes32 id,
    string memory name,
    string memory region,
    address discoveredBy
  ) external;

  function memento__discoverLocation(bytes32 locationId, address discoverer) external;
}
