// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IPositionSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IPositionSystem {
  function memento__setPosition(bytes32 entityId, bytes32 locationId, int32 x, int32 y) external;

  function memento__moveEntity(bytes32 entityId, int32 newX, int32 newY) external;

  function memento__removePosition(bytes32 entityId) external;
}
