// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ITerrainSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ITerrainSystem {
  function memento__setTerrain(bytes32 locationId, uint32 width, uint32 height, bytes memory terrainData) external;

  function memento__getTileType(bytes32 locationId, int32 x, int32 y) external view returns (uint8);

  function memento__isWalkable(bytes32 locationId, int32 x, int32 y) external view returns (bool);
}
