// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { IBaseWorld } from "@latticexyz/world/src/codegen/interfaces/IBaseWorld.sol";
import { ICharacterSystem } from "./ICharacterSystem.sol";
import { IEpisodeSystem } from "./IEpisodeSystem.sol";
import { IEventSystem } from "./IEventSystem.sol";
import { IItemSystem } from "./IItemSystem.sol";
import { ILocationSystem } from "./ILocationSystem.sol";
import { IReputationSystem } from "./IReputationSystem.sol";

/**
 * @title IWorld
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @notice This interface integrates all systems and associated function selectors
 * that are dynamically registered in the World during deployment.
 * @dev This is an autogenerated file; do not edit manually.
 */
interface IWorld is
  IBaseWorld,
  ICharacterSystem,
  IEpisodeSystem,
  IEventSystem,
  IItemSystem,
  ILocationSystem,
  IReputationSystem
{}
