#!/usr/bin/env python3
"""Seed the memento-engine HttpToolProvider in MongoDB.

Usage:
    python scripts/seed_engine_tools.py

Requires MONGO_URI env var pointing to the Bonfires MongoDB.
"""

import os
import sys
from pymongo import MongoClient

PROVIDER = {
    "providerId": "memento-engine",
    "providerName": "Memento Mori Game Engine",
    "description": "Game mechanics tools for NPC agents — combat, skill checks, world queries, world building",
    "enabled": True,
    "baseConfig": {
        "baseUrl": "{{env:MEMENTO_GATEWAY_URL}}",
        "headers": {"Content-Type": "application/json"},
        "auth": {
            "type": "bearer",
            "keyName": "Authorization",
            "valueTemplate": "{{env:ENGINE_API_TOKEN}}",
        },
        "defaultTimeout": 60000,
    },
    "tools": [
        {"id": "mm_get_state", "name": "Get Entity State",
            "description": "Get an entity's current state from the knowledge graph \u2014 HP, inventory, labels, edges, recent events. Call this before responding to check your current condition.",
            "enabled": True,
            "httpConfig": {"endpoint": "/api/engine/state", "method": "POST", "bodyTemplate": {"entity_name": "{{entity_name}}", "npc_id": "{{context:agentId}}"}},
            "inputSchema": {"type": "object", "properties": {"entity_name": {"type": "string", "description": "Entity name to look up"}}, "required": ["entity_name"]},
        },
        {"id": "mm_get_world_time", "name": "Get World Time",
            "description": "Get current in-game time \u2014 moon phase, date, time of day, season.",
            "enabled": True,
            "httpConfig": {"endpoint": "/api/engine/world/time", "method": "GET"},
            "inputSchema": {"type": "object", "properties": {}},
        },
        {"id": "mm_search_world", "name": "Search World",
            "description": "Search the game world's knowledge graph for entities, locations, NPCs, items, relationships, and lore.",
            "enabled": True,
            "httpConfig": {"endpoint": "/api/engine/world/search", "method": "POST", "bodyTemplate": {"query": "{{query}}", "npc_id": "{{context:agentId}}"}},
            "inputSchema": {"type": "object", "properties": {"query": {"type": "string", "description": "Search query"}}, "required": ["query"]},
        },
        {"id": "mm_get_entity", "name": "Get Entity Details",
            "description": "Get detailed information about a specific game entity by name.",
            "enabled": True,
            "httpConfig": {"endpoint": "/api/engine/world/entity", "method": "POST", "bodyTemplate": {"name": "{{name}}", "npc_id": "{{context:agentId}}"}},
            "inputSchema": {"type": "object", "properties": {"name": {"type": "string", "description": "Entity name"}}, "required": ["name"]},
        },
        {"id": "mm_skill_check", "name": "Roll Skill Check",
            "description": "Roll a d20 skill check. Returns PASS or FAIL with margin. Use for persuasion, stealth, lockpicking, any non-combat check.",
            "enabled": True,
            "httpConfig": {"endpoint": "/api/engine/skill-check", "method": "POST", "bodyTemplate": {"skill_level": "{{skill_level}}", "difficulty": "{{difficulty}}", "modifiers": "{{modifiers}}", "npc_id": "{{context:agentId}}"}},
            "inputSchema": {"type": "object", "properties": {"skill_level": {"type": "number", "description": "Skill level (0-30)"}, "difficulty": {"type": "number", "description": "Difficulty class (1-40)"}, "modifiers": {"type": "number", "description": "Situational modifier", "default": 0}}, "required": ["skill_level", "difficulty"]},
        },
        {"id": "mm_calculate_damage", "name": "Calculate Damage",
            "description": "Calculate final damage from weapon damage, strength, and armor.",
            "enabled": True,
            "httpConfig": {"endpoint": "/api/engine/damage", "method": "POST", "bodyTemplate": {"weapon_damage": "{{weapon_damage}}", "attacker_strength": "{{attacker_strength}}", "defender_armor": "{{defender_armor}}", "npc_id": "{{context:agentId}}"}},
            "inputSchema": {"type": "object", "properties": {"weapon_damage": {"type": "number", "description": "Weapon damage"}, "attacker_strength": {"type": "number", "description": "Attacker strength"}, "defender_armor": {"type": "number", "description": "Defender armor"}}, "required": ["weapon_damage", "attacker_strength", "defender_armor"]},
        },
        {"id": "mm_evaluate_disposition", "name": "Evaluate Disposition",
            "description": "Calculate how an interaction shifts friendship and trust.",
            "enabled": True,
            "httpConfig": {"endpoint": "/api/engine/disposition", "method": "POST", "bodyTemplate": {"current_friendship": "{{current_friendship}}", "current_trust": "{{current_trust}}", "interaction_type": "{{interaction_type}}", "npc_id": "{{context:agentId}}"}},
            "inputSchema": {"type": "object", "properties": {"current_friendship": {"type": "number", "description": "Current friendship"}, "current_trust": {"type": "number", "description": "Current trust"}, "interaction_type": {"type": "string", "enum": ["friendly_conversation", "hostile_action", "gift", "betrayal", "help_in_combat", "theft", "trade"], "description": "Interaction type"}}, "required": ["current_friendship", "current_trust", "interaction_type"]},
        },
        {"id": "mm_remember_event", "name": "Remember Event",
            "description": "Record a significant event in the world's memory. Use for deaths, discoveries, betrayals, victories. The world will remember this.",
            "enabled": True,
            "accessCategory": "write",
            "httpConfig": {"endpoint": "/api/engine/world/remember", "method": "POST", "bodyTemplate": {"summary": "{{summary}}", "npc_id": "{{context:agentId}}"}},
            "inputSchema": {"type": "object", "properties": {"summary": {"type": "string", "description": "What happened"}}, "required": ["summary"]},
        },
        {"id": "mm_update_entity", "name": "Update Entity",
            "description": "Update an entity's summary or labels in the knowledge graph.",
            "enabled": True,
            "accessCategory": "write",
            "httpConfig": {"endpoint": "/api/engine/world/update-entity", "method": "POST", "bodyTemplate": {"name": "{{name}}", "new_summary": "{{new_summary}}", "new_labels": "{{new_labels}}", "npc_id": "{{context:agentId}}"}},
            "inputSchema": {"type": "object", "properties": {"name": {"type": "string", "description": "Name"}, "new_summary": {"type": "string", "description": "New summary"}, "new_labels": {"type": "string", "description": "New labels"}}, "required": ["name"]},
        },
        {"id": "mm_give_item", "name": "Give Item",
            "description": "Transfer an item from one entity to another. Use for quest rewards, trades, theft.",
            "enabled": True,
            "accessCategory": "write",
            "httpConfig": {"endpoint": "/api/engine/world/give-item", "method": "POST", "bodyTemplate": {"item_name": "{{item_name}}", "from_entity": "{{from_entity}}", "to_entity": "{{to_entity}}", "npc_id": "{{context:agentId}}"}},
            "inputSchema": {"type": "object", "properties": {"item_name": {"type": "string", "description": "Item name"}, "from_entity": {"type": "string", "description": "From entity"}, "to_entity": {"type": "string", "description": "To entity"}}, "required": ["item_name", "from_entity", "to_entity"]},
        },
        {"id": "mm_give_quest", "name": "Give Quest",
            "description": "Create a quest and assign it to a player.",
            "enabled": True,
            "accessCategory": "write",
            "httpConfig": {"endpoint": "/api/engine/world/give-quest", "method": "POST", "bodyTemplate": {"quest_name": "{{quest_name}}", "description": "{{description}}", "giver_name": "{{giver_name}}", "player_name": "{{player_name}}", "npc_id": "{{context:agentId}}"}},
            "inputSchema": {"type": "object", "properties": {"quest_name": {"type": "string", "description": "Quest name"}, "description": {"type": "string", "description": "Description"}, "giver_name": {"type": "string", "description": "Giver name"}, "player_name": {"type": "string", "description": "Player name"}}, "required": ["quest_name", "description", "giver_name", "player_name"]},
        },
        {"id": "mm_create_npc", "name": "Create NPC",
            "description": "Create a new NPC entity in the world.",
            "enabled": True,
            "accessCategory": "write",
            "httpConfig": {"endpoint": "/api/engine/world/create-npc", "method": "POST", "bodyTemplate": {"name": "{{name}}", "entity_type": "NPC", "summary": "{{summary}}", "location_name": "{{location_name}}", "npc_id": "{{context:agentId}}"}},
            "inputSchema": {"type": "object", "properties": {"name": {"type": "string", "description": "Name"}, "summary": {"type": "string", "description": "Summary"}, "location_name": {"type": "string", "description": "Location name"}}, "required": ["name", "summary"]},
        },
        {"id": "mm_create_item", "name": "Create Item",
            "description": "Create a new item in the world. Use for crafting, forging, finding.",
            "enabled": True,
            "accessCategory": "write",
            "httpConfig": {"endpoint": "/api/engine/world/create-item", "method": "POST", "bodyTemplate": {"name": "{{name}}", "entity_type": "Item", "summary": "{{summary}}", "location_name": "{{location_name}}", "npc_id": "{{context:agentId}}"}},
            "inputSchema": {"type": "object", "properties": {"name": {"type": "string", "description": "Name"}, "summary": {"type": "string", "description": "Summary"}, "location_name": {"type": "string", "description": "Location name"}}, "required": ["name", "summary"]},
        },
        {"id": "mm_create_location", "name": "Create Location",
            "description": "Discover or build a new location in the world.",
            "enabled": True,
            "accessCategory": "write",
            "httpConfig": {"endpoint": "/api/engine/world/create-location", "method": "POST", "bodyTemplate": {"name": "{{name}}", "entity_type": "Location", "summary": "{{summary}}", "npc_id": "{{context:agentId}}"}},
            "inputSchema": {"type": "object", "properties": {"name": {"type": "string", "description": "Name"}, "summary": {"type": "string", "description": "Summary"}}, "required": ["name", "summary"]},
        },
        {"id": "mm_move_to", "name": "Move To Location",
            "description": "ACTUALLY move to a different location in the world. This is the mutation — calling this tool is what makes the move happen and updates the map. Your NPC will not move unless you call this (or mm_move_within for same-room moves). Narrating a move in text does nothing; you must call this tool.",
            "enabled": True,
            "accessCategory": "write",
            "httpConfig": {"endpoint": "/api/engine/world/move", "method": "POST", "bodyTemplate": {"entity_name": "{{entity_name}}", "destination": "{{destination}}", "npc_id": "{{context:agentId}}"}},
            "inputSchema": {"type": "object", "properties": {"entity_name": {"type": "string", "description": "Entity name"}, "destination": {"type": "string", "description": "Destination"}}, "required": ["entity_name", "destination"]},
        },
        {"id": "mm_send_gossip", "name": "Send Gossip",
            "description": "Send a message to another NPC. Creates organic information flow between NPCs.",
            "enabled": True,
            "accessCategory": "write",
            "httpConfig": {"endpoint": "/api/engine/world/gossip", "method": "POST", "bodyTemplate": {"from_npc": "{{from_npc}}", "to_npc": "{{to_npc}}", "message": "{{message}}", "npc_id": "{{context:agentId}}"}},
            "inputSchema": {"type": "object", "properties": {"from_npc": {"type": "string", "description": "From npc"}, "to_npc": {"type": "string", "description": "To npc"}, "message": {"type": "string", "description": "Message"}}, "required": ["from_npc", "to_npc", "message"]},
        },
        {"id": "mm_resolve_combat", "name": "Resolve Combat",
            "description": "Execute full combat resolution: assess, resolve attack/ability, apply consequences, check death. Returns complete outcome with authoritative entity states.",
            "enabled": True,
            "accessCategory": "write",
            "httpConfig": {"endpoint": "/api/engine/combat/resolve", "method": "POST", "bodyTemplate": {"action": "{{action}}", "attacker": "{{attacker}}", "target": "{{target}}", "location": "{{location}}", "context": "{{context}}", "attacker_stats": "{{attacker_stats}}", "target_stats": "{{target_stats}}", "npc_id": "{{context:agentId}}"}},
            "inputSchema": {"type": "object", "properties": {"action": {"type": "string", "description": "Action"}, "attacker": {"type": "string", "description": "Attacker"}, "target": {"type": "string", "description": "Target"}, "location": {"type": "string", "description": "Location"}, "context": {"type": "string", "description": "Context"}, "attacker_stats": {"type": "string", "description": "Attacker stats"}, "target_stats": {"type": "string", "description": "Target stats"}}, "required": ["action", "attacker", "target", "location"]},
        },
        {"id": "mm_assess_combat", "name": "Assess Combat",
            "description": "Evaluate a combat situation without resolving it.",
            "enabled": True,
            "httpConfig": {"endpoint": "/api/engine/combat/assess", "method": "POST", "bodyTemplate": {"action": "{{action}}", "attacker": "{{attacker}}", "target": "{{target}}", "location": "{{location}}", "npc_id": "{{context:agentId}}"}},
            "inputSchema": {"type": "object", "properties": {"action": {"type": "string", "description": "Action"}, "attacker": {"type": "string", "description": "Attacker"}, "target": {"type": "string", "description": "Target"}, "location": {"type": "string", "description": "Location"}}, "required": ["action", "attacker", "target", "location"]},
        },
        {"id": "mm_check_plausibility", "name": "Check Plausibility",
            "description": "DRY RUN ONLY — verifies whether an action is physically valid WITHOUT performing it. DOES NOT mutate game state, DOES NOT move your NPC, DOES NOT resolve combat. This is optional validation before a mutation. After calling this and getting plausible=true, you MUST still call the action's specific mutation tool (mm_move_within, mm_move_to, mm_resolve_combat, etc.) to actually execute the action. Returns {plausible: bool, reason: string}.",
            "enabled": True,
            "httpConfig": {"endpoint": "/api/engine/plausibility", "method": "POST", "bodyTemplate": {"action": "{{action}}", "context": "{{context}}", "npc_id": "{{context:agentId}}"}},
            "inputSchema": {"type": "object", "properties": {"action": {"type": "string", "description": "Action"}, "context": {"type": "string", "description": "Context"}}, "required": ["action", "context"]},
        },
        {"id": "mm_design_quest", "name": "Design Quest",
            "description": "Design a morally complex quest with choices, rewards, and consequences.",
            "enabled": True,
            "accessCategory": "write",
            "httpConfig": {"endpoint": "/api/engine/design/quest", "method": "POST", "bodyTemplate": {"location": "{{location}}", "npc_name": "{{npc_name}}", "player_level": "{{player_level}}", "active_quests": "{{active_quests}}", "faction_context": "{{faction_context}}", "npc_id": "{{context:agentId}}"}},
            "inputSchema": {"type": "object", "properties": {"location": {"type": "string", "description": "Location"}, "npc_name": {"type": "string", "description": "Npc name"}, "player_level": {"type": "number", "default": 1, "description": "Player level"}, "active_quests": {"type": "string", "description": "Active quests"}, "faction_context": {"type": "string", "description": "Faction context"}}, "required": ["location", "npc_name"]},
        },
        {"id": "mm_design_item", "name": "Design Item",
            "description": "Design thematically appropriate items with stats and lore.",
            "enabled": True,
            "accessCategory": "write",
            "httpConfig": {"endpoint": "/api/engine/design/item", "method": "POST", "bodyTemplate": {"location_name": "{{location_name}}", "rarity_budget": "{{rarity_budget}}", "num_items": "{{num_items}}", "npc_id": "{{context:agentId}}"}},
            "inputSchema": {"type": "object", "properties": {"location_name": {"type": "string", "description": "Location name"}, "rarity_budget": {"type": "string", "default": "common", "description": "Rarity budget"}, "num_items": {"type": "number", "default": 1, "description": "Num items"}}, "required": ["location_name"]},
        },
        {"id": "mm_design_npc", "name": "Design NPC",
            "description": "Design a full NPC with personality, stats, and backstory.",
            "enabled": True,
            "accessCategory": "write",
            "httpConfig": {"endpoint": "/api/engine/design/npc", "method": "POST", "bodyTemplate": {"role": "{{role}}", "location_name": "{{location_name}}", "region_context": "{{region_context}}", "npc_id": "{{context:agentId}}"}},
            "inputSchema": {"type": "object", "properties": {"role": {"type": "string", "description": "Role"}, "location_name": {"type": "string", "description": "Location name"}, "region_context": {"type": "string", "description": "Region context"}}, "required": ["role", "location_name"]},
        },
        {"id": "mm_design_location", "name": "Design Location",
            "description": "Design a full location with tile map, secrets, and atmosphere.",
            "enabled": True,
            "accessCategory": "write",
            "httpConfig": {"endpoint": "/api/engine/design/location", "method": "POST", "bodyTemplate": {"location_plan": "{{location_plan}}", "region_name": "{{region_name}}", "npc_id": "{{context:agentId}}"}},
            "inputSchema": {"type": "object", "properties": {"location_plan": {"type": "string", "description": "Location plan"}, "region_name": {"type": "string", "description": "Region name"}}, "required": ["location_plan", "region_name"]},
        },
        {"id": "mm_design_region", "name": "Design Region",
            "description": "Design an entire region with biome, culture, threats, and locations.",
            "enabled": True,
            "accessCategory": "write",
            "httpConfig": {"endpoint": "/api/engine/design/region", "method": "POST", "bodyTemplate": {"theme": "{{theme}}", "adjacent_regions": "{{adjacent_regions}}", "player_level": "{{player_level}}", "npc_id": "{{context:agentId}}"}},
            "inputSchema": {"type": "object", "properties": {"theme": {"type": "string", "description": "Theme"}, "adjacent_regions": {"type": "string", "description": "Adjacent regions"}, "player_level": {"type": "number", "default": 1, "description": "Player level"}}, "required": ["theme"]},
        },
        {"id": "mm_npc_memory", "name": "NPC Memory",
            "description": "Record a first-person memory of a scene from your perspective.",
            "enabled": True,
            "accessCategory": "write",
            "httpConfig": {"endpoint": "/api/engine/npc-memory", "method": "POST", "bodyTemplate": {"summary": "{{summary}}", "npc_id": "{{context:agentId}}"}},
            "inputSchema": {"type": "object", "properties": {"summary": {"type": "string", "description": "Your first-person memory of what happened"}}, "required": ["summary"]},
        },
        {"id": "mm_inventory", "name": "Get Inventory",
            "description": "Get the inventory of any entity (player or NPC). Use to inspect what someone is carrying before trading.",
            "enabled": True,
            "accessCategory": "read",
            "httpConfig": {"endpoint": "/api/engine/inventory", "method": "POST", "bodyTemplate": {"entity_id": "{{entity_id}}", "npc_id": "{{context:agentId}}"}},
            "inputSchema": {"type": "object", "properties": {"entity_id": {"type": "string", "description": "UUID of the entity whose inventory to check"}}, "required": ["entity_id"]},
        },
        {"id": "mm_inventory_transfer", "name": "Transfer Item",
            "description": "Transfer an item from one entity to another. Use for trades, gifts, theft resolution.",
            "enabled": True,
            "accessCategory": "write",
            "httpConfig": {"endpoint": "/api/engine/inventory/transfer", "method": "POST", "bodyTemplate": {"item_id": "{{item_id}}", "from_entity": "{{from_entity}}", "to_entity": "{{to_entity}}", "quantity": "{{quantity}}", "npc_id": "{{context:agentId}}"}},
            "inputSchema": {"type": "object", "properties": {"item_id": {"type": "string", "description": "UUID of the item to transfer"}, "from_entity": {"type": "string", "description": "UUID of current owner"}, "to_entity": {"type": "string", "description": "UUID of new owner"}, "quantity": {"type": "number", "description": "How many to transfer", "default": 1}}, "required": ["item_id", "from_entity", "to_entity"]},
        },
        {"id": "mm_heartbeat", "name": "Trigger Heartbeat",
            "description": "Trigger world evolution \u2014 processes the event stack and generates new content. Call when something significant happens that should evolve the world.",
            "enabled": True,
            "accessCategory": "write",
            "httpConfig": {"endpoint": "/api/engine/heartbeat", "method": "POST", "bodyTemplate": {"npc_id": "{{context:agentId}}"}},
            "inputSchema": {"type": "object", "properties": {}},
        },
        {"id": "mm_world_reaction", "name": "World Reaction",
            "description": "Process world seeds and spawn entities from an episode. Batch-creates NPCs, items, quests, and lore from structured entity seeds.",
            "enabled": True,
            "accessCategory": "write",
            "httpConfig": {"endpoint": "/api/engine/world/react", "method": "POST", "bodyTemplate": {"entities_json": "{{entities_json}}", "location": "{{location}}", "location_uuid": "{{location_uuid}}", "episode_summary": "{{episode_summary}}", "npc_id": "{{context:agentId}}"}},
            "inputSchema": {"type": "object", "properties": {"entities_json": {"type": "string", "description": "JSON array of entity seeds to spawn"}, "location": {"type": "string", "description": "Location name where entities spawn"}, "location_uuid": {"type": "string", "description": "UUID of the location"}, "episode_summary": {"type": "string", "description": "Summary of the episode that triggered this reaction"}}, "required": ["entities_json", "location", "location_uuid"]},
        },
        {"id": "mm_narrate", "name": "Narrate Scene",
            "description": "Run the narration crew to generate immersive environment narration for a scene. Provide the player action, scene context from your world search, and any detected events. Returns polished narrative prose with @username NPC cues. Use this after gathering context via mm_search_world.",
            "enabled": True,
            "accessCategory": "write",
            "httpConfig": {"endpoint": "/api/engine/narrate", "method": "POST", "bodyTemplate": {"action": "{{action}}", "context": "{{context}}", "events": "{{events}}", "mode": "{{mode}}", "npc_id": "{{context:agentId}}"}},
            "inputSchema": {"type": "object", "properties": {"action": {"type": "string", "description": "Player action(s) to narrate"}, "context": {"type": "string", "description": "Scene context from mm_search_world results"}, "events": {"type": "string", "description": "Detected events summary (combat, quest, social, etc.)"}, "mode": {"type": "string", "enum": ["action", "intro", "rejection"], "default": "action", "description": "Narration mode"}}, "required": ["action"]},
        },
        {"id": "mm_trigger_npc", "name": "Trigger NPC",
            "description": "Explicitly trigger a specific NPC to react to the scene. Sends a @tagged Matrix message so the NPC agent wakes up and responds. Use this instead of mentioning NPC names in your text.",
            "enabled": True,
            "accessCategory": "write",
            "httpConfig": {"endpoint": "/api/engine/trigger-npc", "method": "POST", "bodyTemplate": {"npc_name": "{{npc_name}}", "context": "{{context}}", "npc_id": "{{context:agentId}}"}},
            "inputSchema": {"type": "object", "properties": {"npc_name": {"type": "string", "description": "Name of the NPC to trigger (e.g. 'Grumlock Stonebrow')"}, "context": {"type": "string", "description": "What happened that the NPC should react to"}}, "required": ["npc_name"]},
        },
        {"id": "mm_npc_response", "name": "NPC Response",
            "description": "Send in-character dialogue or narration to the game. This is how you speak to players. Call this instead of writing dialogue in your final message.",
            "enabled": True,
            "httpConfig": {"endpoint": "/api/engine/npc-response", "method": "POST", "bodyTemplate": {"dialogue": "{{dialogue}}", "emotion": "{{emotion}}", "target": "{{target}}", "npc_id": "{{context:agentId}}"}},
            "inputSchema": {"type": "object", "properties": {"dialogue": {"type": "string", "description": "What you say, in character"}, "emotion": {"type": "string", "description": "Emotion/tone (e.g. 'gruff', 'suspicious', 'warm')"}, "target": {"type": "string", "description": "Who you're speaking to (optional)"}}, "required": ["dialogue"]},
        },
        {"id": "mm_move_within", "name": "Move Within Room",
            "description": "ACTUALLY move your NPC to a new position within the current room. This is the mutation — calling this tool is what updates the map and fires the move badge. Use to approach a player, back away, patrol, or reposition. Max 5 tiles per move (Manhattan distance). Narrating a move in text does nothing — your NPC will not move unless you call this tool. mm_check_plausibility is a dry run and does NOT substitute for this.",
            "enabled": True, "accessCategory": "write",
            "httpConfig": {"endpoint": "/api/engine/move-within", "method": "POST", "bodyTemplate": {"target_x": "{{target_x}}", "target_y": "{{target_y}}", "npc_id": "{{context:agentId}}"}},
            "inputSchema": {"type": "object", "properties": {"target_x": {"type": "number", "description": "Target x coordinate in the room grid"}, "target_y": {"type": "number", "description": "Target y coordinate in the room grid"}}, "required": ["target_x", "target_y"]},
        },
    ],
}


def main():
    mongo_uri = os.getenv("MONGO_URI")
    db_name = os.getenv("MONGO_DB_NAME", "bonfires_staging")
    if not mongo_uri:
        print("Error: MONGO_URI not set")
        sys.exit(1)

    client = MongoClient(mongo_uri)
    db = client[db_name]
    collection = db["httptoolproviders"]

    # Upsert by providerId
    result = collection.update_one(
        {"providerId": PROVIDER["providerId"]},
        {"$set": PROVIDER},
        upsert=True,
    )

    if result.upserted_id:
        print(f"Created HttpToolProvider: {PROVIDER['providerId']} ({len(PROVIDER['tools'])} tools)")
    else:
        print(f"Updated HttpToolProvider: {PROVIDER['providerId']} ({len(PROVIDER['tools'])} tools)")

    client.close()


if __name__ == "__main__":
    main()
